#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPT_DIR=`pwd`
popd > /dev/null

SERVER_DIR="$SCRIPT_DIR"
MINECRAFT_JAR="$SERVER_DIR/minecraft_server.1.8.6.jar"
JAVA_OPTS="-Xms1G -Xmx1G"

Main()
{
    pushd "$SERVER_DIR"

    # The Minecraft server writes to server.properties as it runs, so to prevent
    # constantly-dirty files in source control, copy over a template.
    cp server.properties.in server.properties

    export INPUT="$SERVER_DIR/input"
    export REAL_INPUT="$SERVER_DIR/input_"
    export OUTPUT="$SERVER_DIR/output"
    export CAPTURE="$SERVER_DIR/capture"

    rm -f "$INPUT" "$REAL_INPUT" "$OUTPUT" "$CAPTURE" || exit 1
    mkfifo "$INPUT" "$REAL_INPUT" "$OUTPUT" || exit 1

    trap CleanUp HUP INT TERM

    ListenIn <> "$INPUT" &
    java $JAVA_OPTS -jar "$MINECRAFT_JAR" nogui <> "$REAL_INPUT" | ListenOut

    CleanUp
}

CleanUp()
{
    rm -f "$INPUT" "$REAL_INPUT" "$OUTPUT" "$CAPTURE"
}

ListenIn()
{
    while read line; do
        echo "INPUT: $line"
        echo "$line" >> "$REAL_INPUT"
    done
}

ListenOut()
{
    while read line; do
        if [ -f "$CAPTURE" ]; then
            echo "CAPTURED: $line"
            echo "$line" >> "$OUTPUT"
        else
            echo "$line"
        fi
    done
}

Main
